### ISSUE TITLE
Preserved/tourism issues

### ISSUE THREAD

**Issue by nathhad** [OpenRailwayMap/OpenRailwayMap-CartoCSS#36] opened 2020-07-21 21:10 UTC
I was working on a preserved/tourism railroad about a week and a half ago, and so far (9 days later) the mainline still doesn't render (with what I understand to be the current appropriate tagging).  Other changes that I made immediately adjacent to service tracks render, and the tile status page shows that the current tile was rendered since my change.

Relevant tagging combo:
railway=rail
railway:preserved=yes
usage=tourism

One sample way in question:
https://www.openstreetmap.org/way/75606128

The current rendering at that location:
https://www.openrailwaymap.org/?lang=null&lat=39.64380475008543&lon=-78.77133429050446&zoom=17&style=standard

Provided my tagging is in fact the supported combination for this use, this may be a rendering combo that just hasn't been addressed yet.  I remember some ongoing discussion on how to render preserved and tourism lines, since we only have so many easily distinguished colors available (which gets even harder when you're slightly colorblind, I already can only tell the light rail and  branch colors apart when they are superimposed immediately side by side, and my colorblindness is mild, so I completely understand the difficulty there).  I don't remember right now if a conclusion was reached in that discussion.

I've also attached a screenshot of the current rendering, with the subject mainline pointed out.
![WMSR Ridgeley 1](https://user-images.githubusercontent.com/12617618/88107225-bb76ee80-cb74-11ea-90ec-016b7fa7e871.png)

Thanks!
Chuck

**Comment by DerDakon** [comment] 2020-07-22 06:25
Duplicate of #7

**Closed by DerDakon** 2020-07-22 06:25 UTC
